---
- name: "Install Consul"
  ansible.builtin.package:
    name: consul-{{ version }}
    state: present

- name: "Version Lock the Consul Package"
  community.general.yum_versionlock:
    name: consul
  when: version_lock