---
# tasks file for server
- name: "Install Consul Binary"
  include_role:
    name: install

- name: "Start and Enable Consul Service"
  ansible.builtin.service:
    name: 'consul'
    state: started
    enabled: yes

- name: "Start and enable Consul Exporter Service"
  ansible.builtin.service:
    name: 'consul_exporter'
    state: started
    enabled: yes
  when: consul_exporter