---
name: "cub_oit_pe.consul.install"
on:
  push:
    paths:
      - 'roles/install/**'
      - '.github/workflows/install.yml'
  pull_request:
    paths:
      - 'roles/install/**'
      - '.github/workflows/install.yml'
jobs:
  molecule:
    runs-on: ubuntu-20.04
    env:
      PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
      ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - distro: rhel8
            image: centos:8
            command: /usr/sbin/init
        collection_role:
          - role_install
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/cub_oit_pe/consul

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          python -m pip install --upgrade pip
          pip install molecule molecule-docker yamllint ansible-lint docker

      - name: Find the latest version of community.general
        run: |
          # credit to https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c#gistcomment-3294173
          cglu=$(curl -fs -o/dev/null -w %{redirect_url} https://github.com/ansible-collections/community.general/releases/latest)
          echo "CG_LATEST=$(basename ${cglu})" >> $GITHUB_ENV

      - name: Cache for community.general
        id: cache-cg
        uses: actions/cache@v2
        with:
          path: ansible_collections/community/general
          key: collection-community.general-${{ env.CG_LATEST }}

      - name: Install collection dependencies
        if: steps.cache-cg.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: ansible-collections/community.general
          ref: refs/tags/${{ env.CG_LATEST }}
          path: ansible_collections/community/general

      - name: Run role test
        env:
          DRIVER: docker
          MOLECULE_COMMAND: ${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
          MOLECULE_IMAGE: ${{ matrix.molecule_distro.image }}
        run: >-
          molecule --version &&
          ansible --version &&
          molecule --debug test -s ${{ matrix.collection_role }}
        working-directory: ansible_collections/cub_oit_pe/consul/tests/integration